server:
  port: 8083
  servlet:
    context-path: /

spring:
  profiles:
    active: ${ENV:local}
  datasource:
    url: jdbc:postgresql://dpg-ct7hjb23esus73bsdnrg-a.virginia-postgres.render.com:5432/belengineersdb
    username: belengineersdb_user
    password: hNXuKlCDjJ0P5gcYpE9RAUDjjC5hxpW9
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_schema: public
      hibernate:
        format_sql: true
        transaction:
          coordinator_class=jdbc
        use_sql_comments: true
logging:
  level:
    org.springframework: INFO






