server:
  port: 8083
  servlet:
    context-path: /

spring:
  profiles:
    active: ${ENV:local}
  datasource:
    url: jdbc:postgresql://dpg-cu19k95svqrc73eprq5g-a.virginia-postgres.render.com:5432/belengineersdb_y15s
    username: belengineers
    password: 1CUDCwbU1KyWDIkTL0sPTX8OfwVBUxiH
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_schema: public
      hibernate:
        format_sql: true
        transaction:
          coordinator_class=jdbc
        use_sql_comments: true
logging:
  level:
    org.springframework: INFO






