server:
  port: 8083
  servlet:
    context-path: /

spring:
  profiles:
    active: ${ENV:local}
  datasource:
    url: jdbc:postgresql://dpg-ctvikfqj1k6c73dmmh60-a.ohio-postgres.render.com:5432/postgres
    username: dbtrasport_user
    password: 7RNoLbMrWrvlohvOX1aKxxGrqez2xQNU
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_schema: public
      hibernate:
        format_sql: true
        transaction:
          coordinator_class=jdbc
        use_sql_comments: true
logging:
  level:
    org.springframework: INFO






